### ISSUE TITLE
IM gonna cry. Unknown error when injecting.

### ISSUE THREAD

**Issue by C0ZZYTHEC0DER** [ItzzExcel/FluxAPI#10]
after the 'unknown error' pop up appear, i try to restart the project and boom:

System.DllNotFoundException: 'Unable to load DLL 'C:\ProgramData\Fluxus\FluxusAPI\FluxteamAPI.dll' or one of its dependencies: The process cannot access the file because it is being used by another process. (0x80070020)'

**Comment by C0ZZYTHEC0DER** [comment]
@ItzzExcel @NotExcelz

**Comment by C0ZZYTHEC0DER** [comment]
after i start it again (in publish version), the unknown error pop up again

**Comment by MrKillingHunter** [comment]
this is normal, dont worry. just hit continue
i had this error before and it doesnt matter (not that i know of)

**Comment by NotExcelz** [comment]
Close Roblox.

**Comment by C0ZZYTHEC0DER** [comment]
> this is normal, dont worry. just hit continue i had this error before and it doesnt matter (not that i know of)

there is no continue button + its still saying me to inject the dll.

**Comment by C0ZZYTHEC0DER** [comment]
> Close Roblox.

can you give more details what I should do after closing roblox?

**Comment by ItzzExcel** [comment]
Please contact me via discord, (itzzexcel) It's awful talk in here.
