### ISSUE TITLE
how to make attach timer

### ISSUE THREAD

**Issue by MrKillingHunter** [ItzzExcel/FluxAPI#6]
is there a variable for attached? eg.

Fluxus.IsInjected

**Comment by MrKillingHunter** [comment]
if there already is a timer for attached, can u teach how to use it?

**Comment by ItzzExcel** [comment]
Are you the guy who asked me this like a week ago?

**Comment by ItzzExcel** [comment]
I'm adding the IsInjected bool at the next time. Give me a few hours.
