### ISSUE TITLE
Ok please help.

### ISSUE THREAD

**Issue by C0ZZYTHEC0DER** [ItzzExcel/FluxAPI#9]
I get this error when try to run my winforms on testing. the error is found inside program.cs.

Could not load file or assembly 'FluxAPI, Version=22.9.2023.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

**Comment by NotExcelz** [comment]
Change your architecture to x86

**Comment by C0ZZYTHEC0DER** [comment]
> Change your architecture to x86

may i ask how? i have try to change it inside properties of the project (platform target) and also the dropdown on top of the bar in VS 2022 (using .NET 6.0)
